name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ritikvirus/springboot_application:first .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.D_USERNAME }} -p ${{ secrets.D_PASS }}

      - name: Push Docker image to Docker Hub
        run: docker push ritikvirus/springboot_application:first
      - name: Push Docker image to Docker Hub
        run: docker push ritikvirus/springboot_application:first

      - name: Deploy to EC2  # <-- Corrected indentation
        env:
            PRIVATE_KEY: ${{ secrets.aws-ssh }}
            HOSTNAME: ${{ secrets.HOST_IP }}
            USER_NAME: ${{ secrets.HOST_USER }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 666 key.pem
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
              
          ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$HOSTNAME "sudo docker rm -f springboot && docker rmi springboot:first s&& udo Docker pull ritikvirus/springboot_application:first && sudo docker run -d -p 8080:8080 ritikvirus/springboot_application:first --name springboot"
