name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: 11

      # - name: Build and package JAR
      #   run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t ritikvirus/springboot_application:first .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.D_USERNAME }} -p ${{ secrets.D_PASS }}

      - name: Push Docker image to Docker Hub
        run: docker push ritikvirus/springboot_application:first
